tokenizer_path: data/tokenizers/wordpiece_70k.json
vocab_size: 70000
mlm_probability:  0.3
output_path: data/lm_models/distilbert_lm_wordpiece_70k
num_train_epochs: 8
learning_rate: 5e-5
batch_size: 32